name: sai-genai-accelerator
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    volumes:
      - ./docker-compose-resources/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm
    ports:
      - 8082:8080
    healthcheck:
      test: "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"
      interval: 5s
      timeout: 5s
      retries: 60

  phoenix:
    image: arizephoenix/phoenix:version-8.26.1
    ports:
      - 6006:6006
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import requests; import sys; sys.exit(0) if requests.get('http://localhost:6006/').status_code == 200 else sys.exit(1)",
        ]
      interval: 1s
      timeout: 10s
      retries: 120
